# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Set up JDK (Java 14)
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: Delete Target (if present)
      run: rm -rf target

    - name: Maven Compile, Test, Report
      run: mvn package
     
    - name: Generate Docs 
      run: mvn javadoc:javadoc
    
    - name: Release Generation
      run: |
        mkdir apidocs
        mv target/site/apidocs apidocs
        tar cvfz apidocs.tar.gz apidocs
        mv apidocs.tar.gz deliverables/
        mkdir release
        mv src release/src
        mv README.md release/
        mv deliverables release/deliverables
        mv pom.xml release/pom.xml


    - name: Push Release 
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: release
        FOLDER : release
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}